version: '3.3'
services:
  postgres-compose:
    image: 'postgres:13.1-alpine'
    environment:
      POSTGRES_USER: "customer"
      POSTGRES_PASSWORD: "postgre"
    ports:
      - "15432:5432"
    volumes:
      - ./data:/data/db
    networks:
      - postgres-compose-network
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgre@email.com"
      PGADMIN_DEFAULT_PASSWORD: "postgre"
    ports:
      - "33002:80"
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge


